### ISSUE TITLE
Fix BWL ibm.biz link

### ISSUE THREAD

**Issue by jgoodhue** [thomasyang44/sko-tech-academy#1]
@thomasyang44 I noticed that your https://ibm.biz/SKOTechAcademyProcess link is set to the wrong BWL link, the team building one instead of the BA labs one (probably my bad giving you the wrong one).  I set it to the right one in the process.md file if you can please fix the ibm.biz link and edit the md back?  Thanks!

**Comment by thomasyang44** [comment]
Thanks - updated!
